'use strict';
const $=id=>document.getElementById(id);
const occasions={just:{name:'Просто так',title:'твоя Вселенная.',label:'Без повода. От всего сердца.',intro:'Иногда самый хороший повод — просто вспомнить, как много человек для тебя значит.',wish:'Пусть среди обычных дней почаще случаются необыкновенно хорошие. С любимыми мелочами, неожиданными радостями и ощущением, что жизнь обнимает тебя в ответ.'},birthday:{name:'День рождения',title:'это твой день.',label:'С днём рождения!',intro:'Сегодня хороший день, чтобы напомнить: твоё появление в этом мире — настоящий подарок.',wish:'С днём рождения! Пусть новый год твоей жизни будет не гонкой за чужими ожиданиями, а дорогой к тому, что радует именно тебя. Желаю здоровья, сил для мечтаний и множества поводов сказать: «Как же сейчас хорошо».'},newyear:{name:'Новый год',title:'навстречу хорошему.',label:'С Новым годом!',intro:'Пусть впереди будет больше тёплых встреч, маленьких чудес и счастливых «помнишь?».',wish:'С Новым годом! Пусть в нём найдётся место и смелым началам, и спокойным вечерам. Пусть хорошее из прошлого останется рядом, а впереди будет то, чего ты ждёшь с надеждой. И пусть на всё это хватит сил и времени.'},nauryz:{name:'Наурыз',title:'пусть всё расцветает.',label:'Наурыз құтты болсын!',intro:'Новое начало, весенний свет и самые добрые пожелания — для тебя.',wish:'Наурыз құтты болсын! Пусть весна принесёт обновление, в доме будет тепло и достаток, а за одним столом чаще собираются дорогие люди. Желаю мира, здоровья и добрых перемен, которым хочется открыть дверь.'},march:{name:'8 Марта',title:'весна начинается с тепла.',label:'С 8 Марта!',intro:'Пусть сегодня будет много внимания, искренних слов и приятных сюрпризов.',wish:'С 8 Марта! Желаю свободы выбирать свой путь, уважения к твоим решениям и радости от каждого маленького достижения. Пусть забота, поддержка и внимание окружают тебя не только в праздник.'},valentine:{name:'14 февраля',title:'о самом нежном.',label:'С Днём всех влюблённых!',intro:'Для слов, которые хочется произносить тихо. И чувств, которыми хочется делиться.',wish:'С Днём всех влюблённых! Пусть любовь будет местом, где спокойно и тепло. Где слышат, берегут и выбирают друг друга каждый день. Пусть для нежности всегда находится время.'},friendship:{name:'День дружбы',title:'как хорошо, что мы знакомы.',label:'С Днём дружбы!',intro:'Некоторые встречи делают жизнь добрее. Наша — одна из них.',wish:'С Днём дружбы! Желаю тебе людей, которым можно написать без повода, с которыми приятно и говорить, и молчать. Пусть расстояния и занятость не забирают у нас простое «Как ты?».'},custom:{name:'Твой особенный день',title:'это стоит отпраздновать.',label:'С твоим особенным днём!',intro:'Есть моменты, которые хочется бережно оставить в памяти. Пусть этот будет одним из них.',wish:'Поздравляю с твоим особенным днём! Пусть за ним последует много нового и хорошего. Желаю успеть насладиться этим моментом — почувствовать радость, выдохнуть и улыбнуться тому, что уже получилось.'}};
const tones={friend:{opening:'Мне нравится, что среди стольких людей мы встретились. Что теперь можно просто написать тебе, поделиться какой-нибудь ерундой, посмеяться или поговорить о важном. Такие вещи кажутся обычными — пока не понимаешь, как много они дают.',middle:'Спасибо за нашу дружбу. За возможность оставаться собой и не подбирать идеальную версию каждого слова. Я ценю тебя, наше общение и то место, которое ты занимаешь в моей жизни.',reasons:['Даже короткий разговор может сделать обычный день приятнее. Мне радостно, что у нас есть возможность делиться друг с другом жизнью.','Мне не нужен идеальный собеседник. Мне интересно именно с тобой: с твоими мыслями, юмором, мечтами и взглядом на мир.','Дружба складывается из небольших моментов. И для меня эти моменты с тобой — совсем не мелочи.'],end:'Спасибо, что мы есть друг у друга. Пусть впереди у нас будет ещё много хороших историй.'},love:{opening:'Иногда я думаю о том, как удивительно: один человек может стать таким важным. Хочется рассказать тебе первым о чём-то хорошем, услышать твой голос и просто знать, как прошёл твой день.',middle:'Я люблю тебя. Не только в красивые моменты и праздничные даты. Мне хочется беречь то, что между нами есть: внимание, доверие, нежность и возможность быть настоящими рядом друг с другом.',reasons:['Мысль о тебе добавляет тепла даже самому обычному дню. Для меня важно, чтобы и тебе рядом со мной было хорошо.','Я люблю в тебе живого человека — с мечтами, настроениями и своим характером. Тебе не нужно заслуживать нежность совершенством.','Для меня любовь — это ещё и внимание к мелочам. Слышать, спрашивать, поддерживать и находить время друг для друга.'],end:'Люблю тебя. Пусть в этом письме останется немного моей нежности, к которой можно вернуться.'},respect:{opening:'Мне хочется сказать тебе то, что в повседневной суете легко оставить невысказанным: я отношусь к тебе с большим уважением. И мне приятно, что в моей жизни есть наше общение.',middle:'Я ценю твою индивидуальность, твой взгляд на вещи и возможность узнавать тебя. Для уважения не обязательно во всём соглашаться — для меня гораздо важнее внимание к человеку и его границам.',reasons:['Мне приятно общаться с тобой. Такие встречи и разговоры добавляют жизни смысла и оставляют после себя хорошие мысли.','У тебя есть свой путь и свой взгляд на мир. Я уважаю твоё право выбирать то, что важно именно тебе.','Хочется, чтобы ты знал: моё доброе отношение — искреннее. Я ценю знакомство с тобой и желаю тебе хорошего.'],end:'С искренним уважением и самыми добрыми пожеланиями. Пусть у тебя всё складывается.'}};
let config={to:'',from:'',holiday:'just',tone:'friend',message:''};let opened=false;let hugs=0;
function normalize(v){const s=(x,n)=>typeof x==='string'?x.slice(0,n):'';return{to:s(v?.to,45),from:s(v?.from,60),holiday:Object.hasOwn(occasions,v?.holiday)?v.holiday:'just',tone:Object.hasOwn(tones,v?.tone)?v.tone:'friend',message:s(v?.message,1800)}}
function encode(v){const bytes=new TextEncoder().encode(JSON.stringify(v));let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')}
function decode(s){if(s.length>20000)throw Error('Too long');return normalize(JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0)))))}
function readHash(){if(location.hash.startsWith('#letter=')){try{config=decode(location.hash.slice(8));return true}catch(e){$('status').textContent='Ссылка повреждена. Можно создать новое письмо.'}}return false}
function render(){const o=occasions[config.holiday],t=tones[config.tone];$('recipient').textContent=config.to?config.to+',':config.holiday==='just'?'Ты — целая':'Для тебя,';$('headline').textContent=config.holiday==='just'?(config.to?'это твоя Вселенная.':'Вселенная.'):o.title;$('intro').textContent=config.holiday==='just'?'Среди миллиардов звёзд и бесконечных расстояний есть кое-что совсем близкое. Моё тепло к тебе.':o.intro;$('occasion-note').textContent=o.intro;$('letter-label').textContent=o.label.toUpperCase();$('salutation').textContent=config.to?config.to+', это тебе.':'Знаешь что?';$('letter-body').replaceChildren();[t.opening,t.middle,config.message,o.wish,'Пожалуйста, не забывай заботиться о себе. Тебе не обязательно всё успевать и всегда быть в хорошем настроении. Можно отдыхать, искать своё и радоваться небольшим шагам. Мне хочется, чтобы в твоей жизни было больше доброты — в том числе к себе.'].filter(Boolean).forEach(text=>{const p=document.createElement('p');p.textContent=text;$('letter-body').append(p)});$('sender').textContent=config.from||'человек, который тебя ценит';t.reasons.forEach((r,i)=>$('reason'+(i+1)).textContent=r);$('closing').textContent=t.end;document.title=(config.to?config.to+', это':'Это')+' для тебя ✧ — Твоя маленькая Вселенная';document.querySelectorAll('.chip').forEach(b=>{const a=b.dataset.holiday===config.holiday;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});document.dispatchEvent(new Event('letter-rendered'));}
Object.entries(occasions).forEach(([key,value])=>{const b=document.createElement('button');b.type='button';b.className='chip';b.dataset.holiday=key;b.textContent=value.name;b.onclick=()=>{config.holiday=key;if(key==='valentine')config.tone='love';render()};$('chips').append(b);const opt=document.createElement('option');opt.value=key;opt.textContent=value.name;$('holiday-input').append(opt)});
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let observer;if('IntersectionObserver'in window){document.body.classList.add('motion');observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});}
let openingTimer=0;let openingBusy=false;
function openLetter(scroll=true){
 if(openingBusy)return;
 const first=!opened,still=reduced.matches||document.body.classList.contains('paused');
 $('story').hidden=false;$('open').classList.add('opened');$('open-hint').textContent='сигнал достиг самого сердца ♡';$('open').setAttribute('aria-label','Перейти к письму');$('replay-envelope').hidden=false;
 if(first){opened=true;document.querySelectorAll('.reveal').forEach(el=>observer?.observe(el));burst(16);}
 clearTimeout(openingTimer);
 if(first&&!still&&scroll){openingBusy=true;$('open').setAttribute('aria-busy','true');document.body.classList.add('opening-letter');}
 openingTimer=setTimeout(()=>{openingBusy=false;$('open').removeAttribute('aria-busy');document.body.classList.remove('opening-letter');if(scroll)$('letter').scrollIntoView({behavior:still?'instant':'smooth',block:'start'});},first&&!still&&scroll?2300:0);
}
$('replay-envelope').onclick=()=>{if(openingBusy)return;clearTimeout(openingTimer);opened=false;$('open').classList.remove('opened');void $('open').offsetWidth;openLetter(true);};
$('open').onclick=()=>openLetter();function openEditor(){$('to-input').value=config.to;$('from-input').value=config.from;$('holiday-input').value=config.holiday;$('tone-input').value=config.tone;$('message-input').value=config.message;$('status').textContent='';$('share-result').hidden=true;$('editor').showModal()}
$('edit').onclick=openEditor;$('footer-edit').onclick=openEditor;$('close').onclick=()=>$('editor').close();$('editor').addEventListener('click',e=>{if(e.target===$('editor')){const r=$('editor').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('editor').close()}});
function readForm(){config=normalize({to:$('to-input').value.trim(),from:$('from-input').value.trim(),holiday:$('holiday-input').value,tone:$('tone-input').value,message:$('message-input').value.trim()});render()}
$('form').onsubmit=e=>{e.preventDefault();readForm();$('editor').close();openLetter(false);$('home').scrollIntoView({behavior:'smooth'})};
$('share').onclick=async()=>{readForm();const url=location.origin+location.pathname+'#letter='+encode(config);$('share-url').value=url;$('share-result').hidden=false;try{await navigator.clipboard.writeText(url);$('status').textContent='Ссылка скопирована! Отправь её человеку — он увидит закрытый конверт с твоим письмом.'}catch(e){$('share-url').focus();$('share-url').select();$('status').textContent='Ссылка готова. Скопируй её из поля выше.'}};
function burst(count=32){if(reduced.matches||document.body.classList.contains('paused'))return;for(let i=0;i<count;i++){const p=document.createElement('span');p.className='particle';p.textContent=['♡','✦','✧','·'][i%4];p.style.setProperty('--x',(Math.random()-.5)*Math.min(innerWidth,1100)+'px');p.style.setProperty('--y',(-150-Math.random()*400)+'px');p.style.setProperty('--r',(Math.random()-.5)*280+'deg');p.style.left=35+Math.random()*30+'%';p.style.top=55+Math.random()*30+'%';$('particles').append(p);setTimeout(()=>p.remove(),2900)}}
$('hug').onclick=()=>{burst();const lines=['Лови. Это всё тебе. И ещё чуть-чуть сверху ♡','Обнимаю словами. Пусть на душе станет теплее.','Улыбка тебе очень идёт. Даже если её сейчас никто не видит.','Тепло не заканчивается. Можно забрать ещё ♡'];$('hug-message').textContent=lines[hugs++%lines.length]};
function progress(){const max=document.documentElement.scrollHeight-innerHeight;$('progress').style.width=(max>0?scrollY/max*100:0)+'%'}addEventListener('scroll',progress,{passive:true});addEventListener('resize',progress);addEventListener('hashchange',()=>{if(readHash()){clearTimeout(openingTimer);openingBusy=false;document.body.classList.remove('opening-letter');render();$('story').hidden=true;opened=false;$('open').classList.remove('opened');$('open-hint').textContent='открой своё послание ↗';scrollTo(0,0)}});const sharedLetter=readHash();render();if(sharedLetter){$("occasion").hidden=true;const next=document.querySelector(".scroll-link");next.href="#letter";next.onclick=e=>{e.preventDefault();openLetter()};}
const noteMessages=['Даже если сегодня получается только маленький шаг — это уже шаг. Побудь к себе добрее. Твоя ценность не измеряется продуктивностью.','Необязательно заранее знать весь путь. Иногда достаточно любопытства и одного небольшого «А почему бы не попробовать?».','Где-то есть человек, который улыбается, вспоминая тебя. И это письмо — очень прямой намёк ♡'];document.querySelectorAll('.note').forEach(button=>{const original=Array.from(button.childNodes).map(n=>n.cloneNode(true));button.setAttribute('aria-pressed','false');button.addEventListener('click',()=>{const flipped=button.classList.toggle('flipped');button.setAttribute('aria-pressed',String(flipped));if(flipped){button.textContent=noteMessages[Number(button.dataset.note)];}else{button.replaceChildren(...original.map(n=>n.cloneNode(true)));}})});
