/* A small procedural universe. No libraries, textures or paid services. */
(()=>{
'use strict';
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
let paused=reduce.matches,visible=!document.hidden,frameId=0,last=0,time=0,force=true;
const button=document.getElementById('motion-toggle');
function updateButton(){document.body.classList.toggle('paused',paused);button.setAttribute('aria-pressed',String(paused));button.setAttribute('aria-label',paused?'Включить анимацию':'Приостановить анимацию');button.title=paused?'Включить анимацию':'Приостановить анимацию';}
button.onclick=()=>{paused=!paused;force=true;updateButton();schedule()};reduce.addEventListener('change',()=>{paused=reduce.matches;updateButton();force=true;schedule()});updateButton();
let width=innerWidth,height=innerHeight,px=0,py=0,targetX=0,targetY=0;
const canvas=document.getElementById('cosmos'),ctx=canvas.getContext('2d');
let stars=[];let meteors=[];let nextMeteor=3;const palettes=['184,201,255','199,161,255','128,227,233','255,207,231'];
function resizeStars(){width=innerWidth;height=innerHeight;const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);if(ctx)ctx.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:width<700?140:280},()=>({x:(Math.random()-.5)*width*2.6,y:(Math.random()-.5)*height*2.6,z:.35+Math.random()*1.8,size:.4+Math.random()*1.2,phase:Math.random()*6.28,color:palettes[Math.floor(Math.random()*palettes.length)]}));force=true;schedule()}
function drawStars(t,dt){if(!ctx)return;ctx.clearRect(0,0,width,height);for(const s of stars){const x=width/2+(s.x-px*15)/s.z,y=height/2+(s.y-py*12)/s.z;const a=.22+.58*(.5+.5*Math.sin(t*.55+s.phase));if(x<0||x>width||y<0||y>height)continue;ctx.fillStyle=`rgba(${s.color},${a})`;ctx.beginPath();ctx.arc(x,y,s.size/s.z,0,Math.PI*2);ctx.fill();if(s.size>1.3&&s.z<.8){ctx.strokeStyle=`rgba(${s.color},${a*.35})`;ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(x-5,y);ctx.lineTo(x+5,y);ctx.moveTo(x,y-5);ctx.lineTo(x,y+5);ctx.stroke()}}
if(!paused&&t>nextMeteor){meteors.push({x:width*(.1+Math.random()*.9),y:Math.random()*height*.3,life:0});nextMeteor=t+7+Math.random()*10}meteors=meteors.filter(m=>m.life<1.4);for(const m of meteors){m.life+=dt;const x=m.x-m.life*330,y=m.y+m.life*160;const a=Math.sin(Math.min(1,m.life/1.4)*Math.PI);const g=ctx.createLinearGradient(x,y,x+110,y-53);g.addColorStop(0,`rgba(206,196,255,${a})`);g.addColorStop(1,'rgba(170,129,255,0)');ctx.strokeStyle=g;ctx.lineWidth=1.3;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+110,y-53);ctx.stroke()}}
const pc=document.getElementById('planet'),scene=document.getElementById('planet-scene');let gl=null,program=null,uniforms={},planetInView=true;
const vertex=`attribute vec2 aPosition;void main(){gl_Position=vec4(aPosition,0.,1.);}`;
const fragment=`precision mediump float;
uniform vec2 uResolution;uniform float uTime;uniform vec2 uPointer;
mat3 rx(float a){float c=cos(a),s=sin(a);return mat3(1.,0.,0.,0.,c,s,0.,-s,c);}mat3 rz(float a){float c=cos(a),s=sin(a);return mat3(c,s,0.,-s,c,0.,0.,0.,1.);}
float hash(vec3 p){p=fract(p*.3183099+vec3(.11,.27,.39));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}
float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}
float sphere(vec3 ro,vec3 rd,float radius){float b=dot(ro,rd),c=dot(ro,ro)-radius*radius,h=b*b-c;if(h<0.)return -1.;return -b-sqrt(h);}
void main(){vec2 uv=(gl_FragCoord.xy-.5*uResolution)/uResolution.y;uv*=1.0;vec3 ro=vec3(0.,0.,5.8),rd=normalize(vec3(uv*4.7,-4.));mat3 tilt=rx(.93+uPointer.y*.10)*rz(-.38+uPointer.x*.10);vec3 qr=tilt*ro,qd=tilt*rd;vec3 light=normalize(vec3(-3.,3.8,4.));float ts=sphere(ro,rd,1.);float closeD=length(cross(ro,rd));float glow=exp(-max(0.,closeD-1.)*6.)*.13;vec3 col=vec3(.40,.27,.77)*glow;float alpha=glow;
float tr=abs(qd.y)>.0001?-qr.y/qd.y:-1.;vec3 rp=qr+qd*tr;float r=length(rp.xz);float ra=0.;vec3 rc=vec3(0.);if(tr>0.&&r>1.28&&r<2.18){float edge=smoothstep(1.28,1.34,r)*(1.-smoothstep(2.10,2.18,r));float bands=.62+.14*sin(r*145.)+.08*sin(r*360.)+.12*sin(r*38.);float gap=1.-.80*exp(-pow((r-1.78)*56.,2.));ra=edge*bands*gap*.78;vec3 worldp=ro+rd*tr;float shadow=sphere(worldp+light*.015,light,1.);float lit=shadow>0.?.16:1.;rc=mix(vec3(.36,.49,.72),vec3(.82,.54,.76),smoothstep(1.3,2.18,r))*lit;rc+=vec3(.38,.22,.45)*pow(max(0.,1.-abs(r-1.4)*8.),3.);}
if(ra>0.&&(ts<0.||tr>ts)){col=mix(col,rc,ra);alpha=max(alpha,ra);}
if(ts>0.){vec3 p=ro+rd*ts;vec3 n=normalize(p);vec3 q=tilt*p;float a=uTime*.055;vec3 tex=vec3(q.x*cos(a)+q.z*sin(a),q.y,-q.x*sin(a)+q.z*cos(a));float turbulence=noise(tex*5.)*.4+noise(tex*12.)*.14;float bands=.5+.5*sin(tex.y*24.+turbulence*8.);vec3 base=mix(vec3(.20,.28,.49),vec3(.65,.47,.76),bands);base=mix(base,vec3(.75,.68,.87),smoothstep(.62,.92,noise(tex*vec3(3.,26.,3.)))*.55);base+=.08*noise(tex*50.);float day=max(0.,dot(n,light));float rim=pow(1.-max(0.,dot(n,-rd)),3.);col=base*(.075+day*.95)+vec3(.42,.51,1.)*rim*.55;col+=vec3(.94,.70,.88)*pow(max(0.,dot(reflect(-light,n),-rd)),28.)*.12;alpha=1.;}
if(ra>0.&&ts>0.&&tr<ts){col=mix(col,rc,ra);alpha=1.;}
float halo=exp(-abs(closeD-1.025)*34.)*.10;if(ts<0.){col+=vec3(.32,.35,.82)*halo;alpha=max(alpha,halo);}
gl_FragColor=vec4(col,alpha);}`;
function initPlanet(){try{gl=pc.getContext('webgl',{alpha:true,antialias:false,premultipliedAlpha:false,powerPreference:'low-power'});if(!gl)return;function compile(type,src){const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS)){gl.deleteShader(sh);throw new Error('Shader unavailable')}return sh}const vs=compile(gl.VERTEX_SHADER,vertex),fs=compile(gl.FRAGMENT_SHADER,fragment);program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error('Shader link unavailable');gl.useProgram(program);const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(program,'aPosition');gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);for(const key of ['uResolution','uTime','uPointer'])uniforms[key]=gl.getUniformLocation(program,key);scene.classList.add('webgl-ready');resizePlanet()}catch(e){gl=null;scene.classList.remove('webgl-ready')}}
function resizePlanet(){if(!gl)return;const rect=pc.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,innerWidth<700?1:1.3);pc.width=Math.max(1,Math.round(rect.width*dpr));pc.height=Math.max(1,Math.round(rect.height*dpr));gl.viewport(0,0,pc.width,pc.height);force=true;schedule()}
function drawPlanet(t){if(!gl||!planetInView)return;gl.useProgram(program);gl.uniform2f(uniforms.uResolution,pc.width,pc.height);gl.uniform1f(uniforms.uTime,t);gl.uniform2f(uniforms.uPointer,px,py);gl.drawArrays(gl.TRIANGLES,0,6)}
scene.addEventListener('pointermove',e=>{const r=scene.getBoundingClientRect();targetX=(e.clientX-r.left)/r.width*2-1;targetY=(e.clientY-r.top)/r.height*2-1;force=true;schedule()},{passive:true});scene.addEventListener('pointerleave',()=>{targetX=targetY=0;force=true;schedule()});
if('IntersectionObserver'in window)new IntersectionObserver(entries=>{planetInView=entries[0].isIntersecting;if(planetInView){force=true;schedule()}}).observe(scene);
pc.addEventListener('webglcontextlost',e=>{e.preventDefault();gl=null;scene.classList.remove('webgl-ready')});pc.addEventListener('webglcontextrestored',()=>{initPlanet();force=true;schedule()});
function schedule(){if(!frameId&&visible)frameId=requestAnimationFrame(tick)}
function tick(now){frameId=0;if(!visible)return;const elapsed=last?now-last:34;if(elapsed<32&&!force){schedule();return}const dt=Math.min(elapsed/1000,.05);last=now;if(!paused)time+=dt;px+=(targetX-px)*.045;py+=(targetY-py)*.045;drawStars(time,paused?0:dt);drawPlanet(time);force=false;if(!paused)schedule()}
document.addEventListener('visibilitychange',()=>{visible=!document.hidden;if(visible){last=0;force=true;schedule()}else if(frameId){cancelAnimationFrame(frameId);frameId=0}});
addEventListener('resize',()=>{resizeStars();resizePlanet()},{passive:true});
document.getElementById('hug').addEventListener('click',()=>{if(paused)return;const wave=document.createElement('div');wave.className='nova-wave';document.body.append(wave);setTimeout(()=>wave.remove(),1800);meteors.push({x:width*.75,y:height*.3,life:0});});
resizeStars();initPlanet();schedule();
})();
