(()=>{
'use strict';
const $=id=>document.getElementById(id);
const meanings={
 warmth:{title:'Тепло',description:'От одного человека свет расходится дальше — и рядом становится уютнее. Так и твоя доброта меняет чей-то день.',test:/^тепл|^добр/iu},
 together:{title:'Рядом',description:'Две звезды находят общую орбиту. Быть рядом — значит замечать друг друга, даже когда между вами расстояние.',test:/^рядом|^вместе|^друж/iu},
 support:{title:'Поддержка',description:'Когда звезда теряет высоту, другая подхватывает её светом. Поддержка — помочь удержаться, когда своих сил мало.',test:/^поддерж|^забот|^беречь/iu},
 dream:{title:'Мечта',description:'Сначала появляется далёкая точка света. Потом — первый шаг к ней. Даже маленькое движение делает мечту ближе.',test:/^мечт|^смел|^шаг/iu},
 love:{title:'Любовь',description:'Два огонька сохраняют свой свет и создают общее сердце. Любить — беречь близость и оставлять друг другу пространство.',test:/^люблю|^любов|^нежн/iu},
 respect:{title:'Уважение',description:'Две разные звезды светят каждая по-своему. Уважать — видеть ценность человека, не требуя стать твоей копией.',test:/^уваж|^индивидуальн/iu}
};
const pattern=/(?<!\p{L})(?:тепл\p{L}*|добр\p{L}*|рядом|вместе|друж\p{L}*|поддерж\p{L}*|забот\p{L}*|беречь|мечт\p{L}*|смел\p{L}*|шаг\p{L}*|люблю|любов\p{L}*|нежн\p{L}*|уваж\p{L}*|индивидуальн\p{L}*)(?!\p{L})/giu;
let activeButton=null,autoTimer=0;let paragraphObserver=null;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
if('IntersectionObserver'in window){paragraphObserver=new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting){e.target.classList.add('words-visible');paragraphObserver.unobserve(e.target)}}},{threshold:.2});}
function decorate(){paragraphObserver?.disconnect();hide();const elements=document.querySelectorAll('#letter-body p, #reason1, #reason2, #reason3, #closing');for(const p of elements){const text=p.textContent;const parts=document.createDocumentFragment();let cursor=0,count=0;for(const match of text.matchAll(pattern)){if(count>=3)break;const key=Object.keys(meanings).find(k=>meanings[k].test.test(match[0]));if(!key)continue;parts.append(document.createTextNode(text.slice(cursor,match.index)));const b=document.createElement('button');b.type='button';b.className='feeling-word word-'+key;b.dataset.meaning=key;b.setAttribute('aria-expanded','false');b.setAttribute('aria-controls','meaning-card');b.title='Увидеть смысл: '+meanings[key].title;b.textContent=match[0];const spark=document.createElement('span');spark.className='word-spark';spark.setAttribute('aria-hidden','true');spark.textContent=key==='love'?'♡':'✦';b.append(spark);b.addEventListener('click',()=>show(key,b));parts.append(b);cursor=match.index+match[0].length;count++;}parts.append(document.createTextNode(text.slice(cursor)));p.replaceChildren(parts);p.classList.add('animated-paragraph');p.classList.remove('words-visible');if(paragraphObserver)paragraphObserver.observe(p);else p.classList.add('words-visible');}}
function show(key,trigger){clearTimeout(autoTimer);if(activeButton)activeButton.setAttribute('aria-expanded','false');activeButton=trigger;trigger.setAttribute('aria-expanded','true');$('meaning-title').textContent=meanings[key].title;$('meaning-description').textContent=meanings[key].description;const scene=$('meaning-scene');scene.className='meaning-scene';void scene.offsetWidth;scene.classList.add('scene-'+key);$('meaning-card').hidden=false;autoTimer=setTimeout(()=>{if(!$('meaning-card').contains(document.activeElement))hide()},12000);}
function hide(){clearTimeout(autoTimer);$('meaning-card').hidden=true;if(activeButton)activeButton.setAttribute('aria-expanded','false');}
$('meaning-close').onclick=()=>{const target=activeButton;hide();target?.focus({preventScroll:true})};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('meaning-card').hidden){const target=activeButton;hide();target?.focus({preventScroll:true})}});document.addEventListener('pointerdown',e=>{if(!$('meaning-card').hidden&&!e.target.closest('.meaning-card,.feeling-word'))hide()});document.addEventListener('letter-rendered',decorate);decorate();
const fs=$('fullscreen');let toastTimer=0;
function notify(message){$('view-status').textContent=message;$('view-status').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('view-status').hidden=true,7000)}
function current(){return document.fullscreenElement||document.webkitFullscreenElement}
function sync(){const on=Boolean(current());fs.setAttribute('aria-pressed',String(on));fs.querySelector('.fs-label').textContent=on?'Выйти из экрана':'На весь экран';fs.title=on?'Выйти из полноэкранного режима (Esc)':'Открыть поздравление без панелей браузера';}
fs.onclick=async()=>{try{if(current()){const exit=document.exitFullscreen||document.webkitExitFullscreen;if(exit)await exit.call(document);}else{const enter=document.documentElement.requestFullscreen||document.documentElement.webkitRequestFullscreen;if(!enter){notify('Этот браузер не поддерживает полноэкранный режим страницы. На компьютере можно нажать F11.');return;}await enter.call(document.documentElement);}sync();}catch(e){notify('Браузер не разрешил полный экран. Попробуй открыть ссылку отдельно; на компьютере можно нажать F11.');}};
document.addEventListener('fullscreenchange',sync);document.addEventListener('webkitfullscreenchange',sync);sync();
})();
