/* Authored procedural scenes. No downloaded images, generated assets or external services. */
(()=>{'use strict';
const clamp=x=>Math.max(0,Math.min(1,x)),ease=x=>{x=clamp(x);return x*x*(3-2*x)},mix=(a,b,p)=>a+(b-a)*p;
const effects=[['Неоновое признание','Электрический импульс проходит по буквам и зажигает вывеску.'],['Наше созвездие','Две звезды сближаются, а их следы собирают твои слова.'],['Письмо от руки','Перо записывает фразу на личном письме.'],['Бумажный секрет','Складки раскрываются и открывают спрятанное послание.'],['Светлячки','Огоньки поднимаются из сада и находят своё место в буквах.'],['Тёплый огонь','От фитиля поднимаются искры и складывают светящееся послание.'],['Плёнка воспоминаний','Проектор протягивает три кадра вашей истории.'],['Мост между нами','Нить от двух берегов соединяется и несёт твои слова.'],['Сад для тебя','Ветви раскрываются, цветы обрамляют личную записку.'],['Снежное письмо','На морозном стекле расчищается место для тёплых слов.'],['Музыка наших дней','Музыкальная шкатулка открывается и поднимает мелодию из букв.'],['Парус мечты','Бумажный кораблик несёт письмо сквозь волны к рассвету.']];
const topics={
just:['Рядом с тобой теплее','Для маленьких моментов, которые много значат',4],friendship:['Спасибо, что ты рядом','Наши истории хочется продолжать',7],custom:['Это только для тебя','Здесь будет наша особенная история',6],birthday:['С днём рождения','Пусть будет больше дней, которые хочется запомнить',10],friendbirthday:['За новые приключения','Самые смешные истории у нас ещё впереди',6],march:['Пусть расцветает радость','Хочу подарить тебе немного весны',8],romance:['Люблю тебя','Мне дорого каждое наше «помнишь?»',0],may7:['Спасибо за твою поддержку','Сила — в заботе и умении беречь',7],newyear:['С новым годом','Пусть дома будет тепло, а рядом — любимые люди',9],september:['Навстречу открытиям','Шаг за шагом сложное становится понятным',2],summer:['Наше маленькое лето','Сохраним тепло этого дня',11],memorial:['Светлая память','То, что дорого, остаётся с нами',5],nauryz:['Наурыз құтты болсын','Пусть новый день принесёт мир и обновление',8],graduation:['Твоя история продолжается','Горжусь твоим путём — и верю в следующий шаг',11],wedding:['Вместе — новый мир','Пусть общий дом начинается с заботы друг о друге',1],anniversary:['Снова выбираю нас','Спасибо за дни, которые стали нашей историей',6],housewarming:['Дому — тепло','Пусть здесь будет место для счастливых воспоминаний',3],newborn:['Добро пожаловать в мир','Столько нежности помещается в маленьких ладонях',10],recovery:['Я рядом','Можно не спешить. Пусть силы возвращаются бережно',4],success:['Ты смог — и это важно','За этим моментом стоят твои усилия',1],halloween:['Маленькая магия для тебя','Пусть этот вечер будет загадочным и добрым',5]};
const looks=[['auto','По оформлению сайта'],['light','Свет и неон'],['ink','Тушь / манга'],['paper','Бумага и тени'],['pixel','Пиксельная графика'],['gold','Тёплое золото']];
function defaults(topic){return topics[topic]||topics.just}function is(id){return /^pack:personal:(?:[0-9]|1[01]):[0-2]$/.test(id||'')}function info(id){const e=effects[+id.split(':')[2]];return[e[0],e[1],'Используй паузу, перемотку или повтор. Текст можно изменить в мастерской.'];}
function words(s){const d=defaults(s.holiday||s.type?.split(':')[1]);const p=s.personal||{};const subst=v=>v.replaceAll('{имя}',s.name||'Для тебя');return {line:subst(p.phrase||d[0]),name:p.phrase?.includes('{имя}')?'':s.name||'Для тебя',memory:subst(p.memory||d[1]),closing:subst(p.ending||'С теплом, '+(s.sender||'от меня'))};}
function palette(s){let look=s.personal?.look||'auto',skin=s.skin||document.body?.dataset?.skin;if(look==='auto')look=['manga','noir','blueprint'].includes(skin)?'ink':['book','postcard','collage','watercolor'].includes(skin)?'paper':skin==='pixel'?'pixel':['artdeco','realism'].includes(skin)?'gold':'light';const topic=s.holiday;return {look,bg:look==='paper'?'#e9dfcc':look==='ink'?'#f0eee8':'#080e20',fg:look==='paper'?'#46362c':look==='ink'?'#161d28':'#fff2e8',accent:look==='ink'?'#242a31':look==='paper'?'#97604b':look==='gold'?'#eec68a':topic==='romance'?'#ff83c2':topic==='newyear'?'#a5e5ff':topic==='nauryz'?'#aee7b3':'#adbbff',dark:look==='paper'||look==='ink'};}
function path(g,pts,color,width=2){g.beginPath();pts.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.strokeStyle=color;g.lineWidth=width;g.stroke();}
function dot(g,x,y,r,c){g.beginPath();g.arc(x,y,Math.max(.1,r),0,Math.PI*2);g.fillStyle=c;g.fill();}
function text(g,value,x,y,size,color,max=840){g.font=`500 ${size}px Georgia,serif`;g.textAlign='center';g.textBaseline='middle';g.fillStyle=color;g.fillText(value,x,y,max);}
function lines(g,value,x,y,size,color,max=820){g.font=`${size}px Georgia`;const result=[];let line='';for(const ch of [...value]){if(ch==='\n'||g.measureText(line+ch).width>max){result.push(line);line=ch==='\n'?'':ch}else line+=ch}if(line)result.push(line);result.forEach((v,i)=>text(g,v,x,y+(i-(result.length-1)/2)*size*1.35,size,color,max));return result;}
function background(g,t,p,id,s){g.fillStyle=p.bg;g.fillRect(0,0,1000,600);if(window.SceneSetting){SceneSetting.draw(g,t,s.holiday||'just',id%3,p.look==='paper'?'paper':'drawing');g.fillStyle=p.dark?'#f0eee8b8':'#080e20bb';g.fillRect(0,0,1000,600);}if(!p.dark){const r=g.createRadialGradient(500,270,10,500,270,530);r.addColorStop(0,id===5?'#42233999':'#20274355');r.addColorStop(1,p.bg+'22');g.fillStyle=r;g.fillRect(0,0,1000,600);}for(let i=0;i<72;i++){const x=(i*137.53)%1000,y=(i*83.17)%570;g.globalAlpha=.12+.15*(.5+.5*Math.sin(t*.55+i));dot(g,x,y,i%5===0?1.5:.65,p.accent);}g.globalAlpha=1;}
function mask(s,w){const key=w.line+'|'+w.name;if(s._letterMask?.key===key)return s._letterMask;const c=document.createElement('canvas');c.width=1000;c.height=600;const g=c.getContext('2d');lines(g,w.line,500,220,w.line.length>60?34:w.line.length>35?43:52,'#fff');text(g,w.name,500,330,67,'#fff');const a=g.getImageData(0,0,1000,600).data,pts=[];for(let y=100;y<415;y+=5)for(let x=60;x<940;x+=5)if(a[(y*1000+x)*4+3]>100)pts.push([x,y]);return s._letterMask={key,canvas:c,pts};}
function message(g,w,p,t,start=4){g.save();g.globalAlpha=ease((t-start)/1);lines(g,w.memory,500,490,23,p.fg,810);text(g,w.closing,500,560,19,p.accent);g.restore();}
function mainText(g,w,p,a=1){g.save();g.globalAlpha=a;lines(g,w.line,500,220,w.line.length>60?34:w.line.length>35?43:52,p.fg);text(g,w.name,500,330,67,p.accent);g.restore();}
function drawNative(s,t){const g=s.ctx,id=+s.type.split(':')[2],p=palette(s),w=words(s);t=Math.max(0,Math.min(12,t));g.save();background(g,t,p,id,s);
if(id===0){ // glass tube lettering with a travelling electrical front
 const m=mask(s,w),front=mix(55,950,ease(t/3.2));g.globalAlpha=.13;mainText(g,w,p);g.globalAlpha=1;g.save();g.beginPath();g.rect(0,0,front,420);g.clip();if(!p.dark){g.shadowColor=p.accent;g.shadowBlur=20;}mainText(g,w,p);g.restore();if(t<3.2){dot(g,front,330,5,'#fff');for(let i=0;i<18;i++)dot(g,front-i*3,330+Math.sin(i*1.7+t*13)*i,1.5,p.accent);}path(g,[[90,390],[90,410],[910,410],[910,390]],p.accent,1);message(g,w,p,t);
}else if([1,4,5].includes(id)){const m=mask(s,w),progress=ease((t-.3)/3.9);if(id===5){g.fillStyle='#d4bda1';g.fillRect(914,396,28,98);path(g,[[928,400],[928,382]],p.fg,3);g.save();g.translate(928,367);g.scale(1+Math.sin(t*4)*.08,1);g.beginPath();g.moveTo(0,-28);g.bezierCurveTo(28,0,18,29,0,30);g.bezierCurveTo(-17,24,-22,5,0,-28);g.fillStyle=p.accent;g.fill();g.restore();}if(id===4){for(let k=0;k<24;k++){const x=k*44;path(g,[[x,600],[x+Math.sin(t+k)*12,535-k%4*14]],p.accent,1);}}
 for(let i=0;i<m.pts.length;i++){const [tx,ty]=m.pts[i],a=i*2.399,delay=(i%13)*.013,u=ease((progress-delay)/(1-delay));let sx,sy;if(id===1){sx=500+Math.cos(a)*(430+i%90);sy=290+Math.sin(a)*260;}else if(id===4){sx=i*73%1000;sy=620+i%60;}else{sx=928+Math.sin(a)*10;sy=365;}const x=mix(sx,tx,u)+Math.sin(a+t*1.4)*16*(1-u),y=mix(sy,ty,u)-Math.sin(u*Math.PI)*(id===5?180:55);g.globalAlpha=.45+.5*u;dot(g,x,y,1.2+u*.7,p.accent);}g.globalAlpha=1;if(progress>.97)mainText(g,w,p,ease((t-4.1)/.65));if(id===1){for(let k=0;k<2;k++){const x=mix(k?930:70,k?850:150,ease(t/2));dot(g,x,100,4,p.fg);}}message(g,w,p,t,5);
}else if(id===2){g.save();g.translate(500,285);g.rotate(-.035);g.fillStyle=p.dark?'#fffaf0':'#e4dbc7';g.shadowColor='#0006';g.shadowBlur=24;g.fillRect(-430,-205,860,360);g.shadowBlur=0;g.translate(-500,-285);const dark={...p,fg:'#493c36',accent:'#9b554e'},u=ease(t/4),front=85+830*u;g.save();g.beginPath();g.rect(65,80,front-65,380);g.clip();mainText(g,w,dark);g.restore();if(t<4){path(g,[[front,340],[front+35,235]],'#b78959',8);path(g,[[front,340],[front-3,350]],'#232330',3);}g.restore();message(g,w,p,t,4.4);
}else if(id===3){const u=ease(t/3);g.fillStyle=p.dark?'#faf3e1':'#d9c4a8';g.shadowColor='#0008';g.shadowBlur=22;g.fillRect(115,95,770,340);g.shadowBlur=0;mainText(g,w,{...p,fg:'#453537',accent:'#a45a64'},ease((u-.3)/.5));for(const side of [-1,1]){g.save();g.translate(side<0?115:885,95);g.scale(side<0?1:-1,1);g.beginPath();g.moveTo(0,0);g.lineTo(385*(1-u),170);g.lineTo(0,340);g.closePath();g.fillStyle=side<0?'#c1aa90':'#e8d7b9';g.fill();g.restore();}g.save();g.translate(115,95);g.beginPath();g.moveTo(0,0);g.lineTo(770,0);g.lineTo(385,170*(1-u));g.closePath();g.fillStyle='#f0dec0';g.fill();g.restore();message(g,w,p,t);
}else if(id===6){ // projector gate and three distinct personal frames
 const values=[w.line,w.memory,w.closing],phase=Math.min(2,Math.floor(t/3.2)),u=(t-phase*3.2)/3.2;g.fillStyle='#050708';g.fillRect(50,70,900,455);g.save();g.beginPath();g.rect(72,98,856,393);g.clip();const drift=u<.15?(1-ease(u/.15))*-410:0;g.translate(0,drift);g.fillStyle=p.dark?'#d7c7af':'#252138';g.fillRect(85,106,830,380);for(let i=0;i<12;i++){g.fillStyle=p.accent;g.globalAlpha=.05;g.fillRect(100+i*73,106,1,380);}g.globalAlpha=1;text(g,'НАША ИСТОРИЯ · '+(phase+1)+' / 3',500,156,16,p.accent);lines(g,values[phase],500,275,phase===1?32:47,p.fg,750);text(g,w.name,500,408,34,p.accent);g.restore();for(let i=0;i<18;i++){g.fillStyle=p.bg;g.fillRect(70+i*49,80,23,12);g.fillRect(70+i*49,501,23,12);}text(g,'Моменты, к которым хочется вернуться',500,563,20,p.fg);
}else if(id===7){const u=ease(t/3);for(let side=0;side<2;side++){const points=[];for(let j=0;j<=70;j++){const f=j/70*u;points.push([side?930-430*f:70+430*f,410-Math.sin(f*Math.PI/2)*60]);}path(g,points,p.accent,3);dot(g,side?930:70,410,8,p.fg);}if(u>.97)dot(g,500,350,7,p.fg);g.save();g.translate(0,-45);mainText(g,w,p,ease((t-2.5)/1.5));g.restore();message(g,w,p,t);
}else if(id===8){for(let k=0;k<12;k++){const side=k<6?-1:1,j=k%6,u=ease((t-j*.12)/2.2),base=500+side*390,tip=500+side*(350-j*34),ty=380-j*47;g.beginPath();g.moveTo(base,570);g.quadraticCurveTo(base+side*35,ty+60, mix(base,tip,u),mix(570,ty,u));g.strokeStyle=p.accent;g.lineWidth=2;g.stroke();if(u>.8){g.save();g.translate(tip,ty);g.rotate(Math.sin(t+j)*.07);for(let q=0;q<5;q++){g.rotate(Math.PI*2/5);g.beginPath();g.ellipse(0,-10,6,12,0,0,Math.PI*2);g.fillStyle=p.accent;g.globalAlpha=ease((u-.8)*5);g.fill();}g.restore();g.globalAlpha=1;}}mainText(g,w,p,ease((t-2)/1.2));message(g,w,p,t);
}else if(id===9){const u=ease(t/3);g.fillStyle=p.dark?'#d7e4e5':'#1b3549';g.fillRect(70,75,860,380);g.save();g.beginPath();g.rect(95,95,810*u,340);g.clip();mainText(g,w,p);g.restore();for(let i=0;i<85;i++){const x=i*61%890+55,y=(i*47+t*(12+i%13))%570;dot(g,x,y,1+i%3,p.fg);}path(g,[[65,72],[935,72],[935,460],[65,460],[65,72]],p.accent,5);message(g,w,p,t);
}else if(id===10){const u=ease(t/2);g.fillStyle='#674957';g.fillRect(335,365,330,98);g.fillStyle='#b88d7e';g.fillRect(325,355,350,18);g.save();g.translate(325,355);g.scale(1,Math.max(.04,1-u));g.fillStyle='#947384';g.fillRect(0,-100,350,100);g.restore();for(let i=0;i<16;i++){const age=(t*.45+i*.13)%2,x=(i%2?740:245)+Math.sin(age*2+i)*22,y=350-age*120;g.globalAlpha=(1-age/2)*u;dot(g,x,y,4,p.accent);path(g,[[x+4,y],[x+4,y-18]],p.accent,1.5);}g.globalAlpha=1;g.save();g.translate(0,-70);mainText(g,w,p,ease((t-1.5)/2));g.restore();message(g,w,p,t);
}else{const u=ease(t/4),x=mix(-130,500,u),y=420+Math.sin(t*1.4)*7;for(let layer=0;layer<4;layer++){const pts=[];for(let x=0;x<=1000;x+=10)pts.push([x,400+layer*39+Math.sin(x*.012+t*.8+layer)*13]);path(g,pts,p.accent,1+layer*.2);}g.save();g.translate(x,y);g.rotate(Math.sin(t)*.04);g.beginPath();g.moveTo(-85,0);g.lineTo(75,0);g.lineTo(40,42);g.lineTo(-45,42);g.closePath();g.fillStyle='#e9d8c0';g.fill();g.beginPath();g.moveTo(0,0);g.lineTo(0,-85);g.lineTo(65,0);g.fillStyle='#fff4e0';g.fill();g.restore();g.save();g.translate(0,-30);mainText(g,w,p,ease((t-2.4)/1.6));g.restore();message(g,w,p,t,4.7);}
g.restore();}
function draw(s,t){if(palette(s).look!=='pixel')return drawNative(s,t);if(!s._pixelScene){s._pixelScene=document.createElement('canvas');s._pixelScene.width=250;s._pixelScene.height=150;}const g=s._pixelScene.getContext('2d');g.setTransform(.25,0,0,.25,0,0);const copy={...s,ctx:g};drawNative(copy,t);s._letterMask=copy._letterMask;s.ctx.save();s.ctx.imageSmoothingEnabled=false;s.ctx.drawImage(s._pixelScene,0,0,1000,600);s.ctx.restore();}
const original={draw:AnimationPacks.draw,info:AnimationPacks.info,duration:AnimationPacks.duration};AnimationPacks.draw=(s,t)=>is(s.type)?draw(s,t):original.draw(s,t);AnimationPacks.info=id=>is(id)?info(id):original.info(id);AnimationPacks.duration=id=>is(id)?12:original.duration(id);
window.PersonalScenes={effects,looks,topics,defaults,is,words,draw};
})();
