/* Real-time PBR geometry. No photographs or video backgrounds. */
import * as T from './vendor/three.module.js';
export function createWorld(canvas,config){
const renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.4));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
const scene=new T.Scene();scene.background=new T.Color('#17202c');const camera=new T.PerspectiveCamera(38,1,.1,80);let yaw=.2,pitch=.58,distance=6.4,drag=null;
const materials=[],geometries=[];const mat=(color,roughness=.5,metalness=0)=>{const m=new T.MeshPhysicalMaterial({color,roughness,metalness,clearcoat:metalness?.25:.08});materials.push(m);return m;};
const woodCanvas=document.createElement('canvas');woodCanvas.width=512;woodCanvas.height=512;const wg=woodCanvas.getContext('2d');wg.fillStyle='#795339';wg.fillRect(0,0,512,512);for(let i=0;i<640;i++){wg.strokeStyle=i%3?'#573a292b':'#b8946529';wg.lineWidth=.6+i%3;wg.beginPath();for(let x=0;x<=512;x+=8){const y=i*.8+Math.sin(x*.014+i*.17)*3+Math.sin(x*.031+i)*.9;x?wg.lineTo(x,y):wg.moveTo(x,y);}wg.stroke();}const woodTex=new T.CanvasTexture(woodCanvas);woodTex.colorSpace=T.SRGBColorSpace;woodTex.wrapS=woodTex.wrapT=T.RepeatWrapping;woodTex.repeat.set(2,2);
const wood=mat('#ffffff',.55);wood.map=woodTex;const brass=mat('#b69755',.24,.88),paper=mat('#eee5d2',.83),red=mat('#a64949',.55),ceramic=mat('#cbd8d4',.22),green=mat('#386342',.7),ink=mat('#243342',.55);
function mesh(geometry,material,x=0,y=0,z=0,parent=scene){geometries.push(geometry);const o=new T.Mesh(geometry,material);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;parent.add(o);return o;}
const box=(w,h,d,m,x,y,z,parent)=>mesh(new T.BoxGeometry(w,h,d),m,x,y,z,parent);
const cylinder=(rt,rb,h,m,x,y,z,parent)=>mesh(new T.CylinderGeometry(rt,rb,h,64),m,x,y,z,parent);
const sphere=(r,m,x,y,z,parent)=>mesh(new T.SphereGeometry(r,40,28),m,x,y,z,parent);
const torus=(r,t,m,x,y,z,parent)=>mesh(new T.TorusGeometry(r,t,16,80),m,x,y,z,parent);
box(7,.16,4.6,wood,0,-.08,0);box(8,4,.1,mat('#293746',.9),0,1.8,-2.5);
scene.add(new T.HemisphereLight('#d6e5ff','#403222',2));const key=new T.SpotLight('#ffe0a5',42,15,Math.PI/4,.55,1.5);key.position.set(-2,4,2);key.target.position.set(0,0,0);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.bias=-.0001;key.shadow.normalBias=.02;scene.add(key,key.target);const fill=new T.DirectionalLight('#91baff',2.8);fill.position.set(3,3,-3);scene.add(fill);
const environment=new T.Scene();environment.background=new T.Color('#59636c');for(const [x,y,z,w,h] of [[-3,3,1,2,4],[2,4,-2,3,3]]){const p=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({color:'#fff2df',side:T.DoubleSide}));p.position.set(x,y,z);p.lookAt(0,0,0);environment.add(p);}const pmrem=new T.PMREMGenerator(renderer),env=pmrem.fromScene(environment,.05);scene.environment=env.texture;environment.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});pmrem.dispose();
// A hinged envelope, not a scaled image.
const letter=new T.Group();letter.position.set(0,.04,.35);letter.rotation.y=-.12;scene.add(letter);box(1.75,.035,1.02,paper,0,0,0,letter);const sheet=box(1.46,.015,.84,paper,0,.035,-.025,letter);const hinge=new T.Group();hinge.position.set(0,.03,-.51);letter.add(hinge);const triangle=new T.BufferGeometry();triangle.setAttribute('position',new T.Float32BufferAttribute([-.875,0,0,.875,0,0,0,0,.8],3));triangle.computeVertexNormals();const flapmat=paper.clone();flapmat.side=T.DoubleSide;materials.push(flapmat);mesh(triangle,flapmat,0,0,0,hinge);const wax=cylinder(.11,.115,.035,red,0,.065,.08,letter);
hinge.add(wax);wax.position.set(0,.035,.59);
// A ceramic cup with a real hollow profile and coffee surface.
const cup=new T.Group();cup.position.set(1.35,.025,.25);scene.add(cup);const profile=[[.02,0],[.28,0],[.32,.06],[.35,.5],[.32,.53],[.295,.49],[.265,.09],[.02,.09]].map(([x,y])=>new T.Vector2(x,y));mesh(new T.LatheGeometry(profile,64),ceramic,0,0,0,cup);const handle=torus(.19,.045,ceramic,.35,.29,0,cup);cylinder(.291,.29,.012,mat('#251611',.2),0,.435,0,cup);const saucer=cylinder(.48,.44,.04,ceramic,0,-.005,0,cup);
// Practical brass lamp: no unsupported floating components.
cylinder(.35,.39,.07,brass,-1.55,.035,-.75);cylinder(.035,.035,1.6,brass,-1.55,.88,-.75);const shade=cylinder(.23,.56,.48,brass,-1.55,1.8,-.75);const bulb=mat('#fff0c5',.2);bulb.emissive=new T.Color('#ffdda2');bulb.emissiveIntensity=2;sphere(.13,bulb,-1.55,1.58,-.75);
const topic=config.holiday||'just';let ornament=null;
if(['newyear','newborn'].includes(topic)){cylinder(.5,.56,.15,brass,.6,.075,-1.1);const glass=mat('#d5e9f3',.08);glass.transmission=.95;glass.thickness=.09;glass.ior=1.45;glass.transparent=true;glass.opacity=.65;ornament=sphere(.48,glass,.6,.62,-1.1);sphere(.18,paper,.6,.34,-1.1);sphere(.12,paper,.6,.61,-1.1);sphere(.075,paper,.6,.79,-1.1);}
else if(['wedding','anniversary','romance'].includes(topic)){box(.85,.15,.65,ink,.55,.075,-1.15);const a=torus(.2,.045,brass,.4,.24,-1.14),b=torus(.2,.045,brass,.72,.24,-1.18);a.rotation.x=.65;b.rotation.x=-.55;}
else if(['september','graduation'].includes(topic)){for(let j=0;j<3;j++){box(.95,.13,.65,j%2?red:ink,.5,.08+j*.16,-1.1);box(.89,.09,.62,paper,.5,.09+j*.16,-1.08);}}
else if(topic==='birthday'||topic==='friendbirthday'){cylinder(.42,.42,.38,paper,.55,.21,-1.05);cylinder(.45,.45,.04,red,.55,.42,-1.05);for(let j=0;j<3;j++){cylinder(.025,.025,.25,ceramic,.35+j*.2,.565,-1.05);sphere(.035,bulb,.35+j*.2,.71,-1.05);}}
else {cylinder(.2,.27,.47,ceramic,.55,.25,-1.15);for(let j=0;j<5;j++){const x=.55+Math.cos(j*2.4)*.2,z=-1.15+Math.sin(j*2.4)*.16,h=.7+j*.045;cylinder(.011,.011,h,green,x,.47+h/2,z);for(let k=0;k<6;k++){const petal=sphere(.095,j%2?red:paper,x+Math.cos(k*Math.PI/3)*.1,.47+h,z+Math.sin(k*Math.PI/3)*.1);petal.scale.set(1,.42,1);}sphere(.048,brass,x,.49+h,z);}}
let opened=false;const down=e=>{drag={x:e.clientX,y:e.clientY,moved:false};canvas.setPointerCapture?.(e.pointerId);};const move=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>2)drag.moved=true;yaw+=dx*.006;pitch=Math.max(.25,Math.min(1.1,pitch+dy*.004));drag.x=e.clientX;drag.y=e.clientY;Universe.wake();};const up=()=>{if(drag&&!drag.moved)opened=!opened;drag=null;Universe.wake();};canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);
let opening=0;function render(dt,paused){const r=canvas.getBoundingClientRect();if(!r.width)return;const width=Math.max(1,Math.round(r.width)),height=Math.max(1,Math.round(r.height));if(canvas._width!==width||canvas._height!==height){renderer.setSize(width,height,false);canvas._width=width;canvas._height=height;camera.aspect=width/height;camera.updateProjectionMatrix();}const target=opened?1:0;if(paused)opening=target;else opening+=(target-opening)*Math.min(1,dt*5);hinge.rotation.x=-opening*2.7;sheet.position.z=-.025-opening*.35;camera.position.set(Math.sin(yaw)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*distance);camera.lookAt(0,.25,-.15);renderer.render(scene,camera);}
return {render,toggle(){opened=!opened;Universe.wake();},dispose(){canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up);for(const g of geometries)g.dispose();for(const m of materials)m.dispose();woodTex.dispose();env.dispose();renderer.dispose();},scene};
}
